#spring.datasource.url=jdbc:mysql://localhost:3306/task_manager
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.dialect.storage_engine=innodb
#
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
spring:
  datasource:
    password: 'root'
    url: jdbc:mysql://localhost:3306/task_manager
    username: 'root'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true